### PR TITLE
asn1crt and C generator warnings fixes

### PR DESCRIPTION
**Pull request by hcorg**
I've run `clang -Weverything` on asn1crt and some generated code and it did discover some warnings, including C standard naming convention violations.

As a result I've made asn1crt more encapsulated as it now uses more `static` local functions

### CODE REVIEW

**Comment by ttsiodras** [comment]
Hi Konrad - nice cleanup, but it seems it doesn't merge cleanly. 

Can you have a look?

**Comment by hcorg** [comment]
did it merge ok? I received some notification from you I can find now on github :)

**Comment by ttsiodras** [comment]
It did, yes :-) 

Apparently, GitHub fluke - the second time I tried, they realized there was no conflict (you worked on the HEAD, so why would it?)

Thanks!

**Comment by hcorg** [comment]
no problem - better solution for future would require some more refactoring - some functions are used in acn.c and ber.c (and are reported as warnings), so maybe they either should be explicit mentioned in asn1crt.h or another header should be added

**Comment by maxime-esa** [comment]
By the way I am not completely sure what is the status of the BER support. We never used it in taste, I do not know if it was ever tested.

**Comment by hcorg** [comment]
oh, I do not use BER, yet ber.c is required to link acn.c....

**Pull request merged**
