### PR TITLE
C code gen: same ENUMERATED can be used in multiple CHOICEs as ACN encoding determinant

### PR DESCRIPTION
**Pull request by hcorg**

### CODE REVIEW

**Comment by hcorg** [comment]
I've added test case that fails without my change, all other cases passed. No idea why `uniqueName` was used there (as it might contain name of the struct and enum)

**Comment by echatzig** [comment]
Hi Konrad,
     it seems that your patch does not solve the problem. Based on the
inline ACN spec I tried the below

Asn1f2 -c -atc -uPER -ACN 1.asn 1.acn

but although the ASN compiler does not produce an error, the generated code
does not compile

cc -c -g -Wall -Wextra -D_DEBUG -I . -O0 -fprofile-arcs -ftest-coverage -o
1.o 1.c
1.c: In function ‘ChoiceOne_ACN_Decode’:
1.c:485:14: error: ‘a1’ undeclared (first use in this function)
         case a1:
              ^
1.c:485:14: note: each undeclared identifier is reported only once for each
function it appears in
1.c: In function ‘ChoiceTwo_ACN_Decode’:
1.c:656:14: error: ‘a1’ undeclared (first use in this function)
         case a1:
              ^


with 1.asn being:

TEST-CASE DEFINITIONS AUTOMATIC TAGS::= BEGIN

ChoiceSelector ::= ENUMERATED
{
  a1,
  a2
}

MyEnum ::= ENUMERATED
{
  a1,
  b1
}

TestType ::= INTEGER(0..255)

ChoiceOne ::= CHOICE
{
  a1 TestType,
  a2 TestType
}

ChoiceTwo ::= CHOICE
{
  a1 TestType,
  a2 TestType
}

END

and  1.acn as:

TEST-CASE DEFINITIONS ::=
BEGIN
        ChoiceSelector [size 8, encoding pos-int]
        TestType [size 8, encoding pos-int]
        ChoiceOne<ChoiceSelector:sel> [determinant sel]
        ChoiceTwo<ChoiceSelector:sel> [determinant sel]
END

**Comment by hcorg** [comment]
strange - it does pass when I run `make -C Tests` and it works fine with my ASN.1/ACN project.

I've just noticed:  In your example there is a second ENUMERATED with same field name as previous one? Maybe that's causing additional problem?

**Comment by echatzig** [comment]
exactly, the second ENUM is to illustrate the need for uniqueName
If you remove it, the compiler generates code that compiles and runs
correctly but the patch is not sufficient
as it cannot handle more complex cases as this one (second ENUM)

this case needs further investigation - we will create a ticket

On Wed, Jun 10, 2015 at 2:12 PM, Konrad Grochowski <notifications@github.com

**Comment by hcorg** [comment]
I was able to reproduce 'two enums with same contents' problem on master, so my patch fixes part of a bigger issue

**Comment by hcorg** [comment]
I've pushed another test case and fix for it

**Comment by maxime-esa** [comment]
Thanks! 
Elias: Can we merge then? Is everything fixed?

**Comment by maxime-esa** [comment]
Corresponding Mantis bug: http://taste.tuxfamily.org/mantis/view.php?id=436

**Comment by hcorg** [comment]
merged with master; conflicts resolved

**Pull request merged**
