### PR TITLE
Removed self-referenced submodule

### PR DESCRIPTION
**Pull request by hcorg**
no idea what this empty folder was doing in repo, but it disappeared after `git clean -xfd` so maybe it's not needed at all.

### CODE REVIEW

**Comment by ttsiodras** [comment]
I don't get it... CircleCI apparently decided not to trigger with this PR (where as it did with all the others!)

(sigh)

**Comment by hcorg** [comment]
maybe because it did not found any changed files in it? I'm pretty surprised that this folder even existed - there's no way to commit empty directory into git repo, so it must have been something special. Like submodule. But .gitsubmodule file was not present. Aaaand what's a point to made submodule of itself...

**Comment by ttsiodras** [comment]
No, there was no submodule. Away from keyboard, so I can't check - but I am
guessing this folder used to have files that were removed. Will try merging
when I get home...

**Comment by hcorg** [comment]
but in Git there is no such thing as "directory" - only files are in repo. Empty directories disappear by definition. Also check how GitHub displays diff for that commit: "Submodule asn1scc deleted from e467a5 "

Magic :D

**Comment by ttsiodras** [comment]
If I said "no clue", it would be an understatement. As you saw, there were no submodules here...

Oh well :-) Merging.

**Pull request merged**
