### PR TITLE
Remove hardcoded html

### PR DESCRIPTION
**Pull request by maxime-esa**
The HTML code representing the ASN.1 and ACN input grammars, which was placed at the end of the generated ICD documents, was hardcoded in the file Antlr/Comments.cs

I refactored this code from C# to F# and replaced the hardcoded part with use of templates.

Please review the code, mainly function "let PrintFile3 (r:AstRoot) (acn:AcnTypes.AcnAstResolved)" in icdAcn.fs and "let colorize (t: IToken, idx: int, tasses: string array, blueTassesWithLoc: (string*int*int) array)"  in icdUper.fs - thanks

### CODE REVIEW

**Comment by ttsiodras** [comment]
- Nice currying in colorize :-) Python's "partial" is a poor substitute :-(
- May I suggest that you target all HTML entities and not just the less/greater than (in safeText)?
It's a nice opportunity for a fold on a list of all HTML entities... just in case.
- In cases of boolean match (+277), I think a ternary is a better match than.... a match :-)
- containedin and safeText seem to be copied in many places - why not have the one and re-use?

**Comment by ttsiodras** [comment]
Commented on github - hope you got the relevant mail.

On Wed, Apr 29, 2015 at 6:11 PM, maxime-esa <notifications@github.com>
wrote:

> Merged #27 <https://github.com/ttsiodras/asn1scc/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ttsiodras/asn1scc/pull/27#event-293163222>.
>



-- 
e-mail: ttsiodras@gmail.com
web: http://users.softlab.ntua.gr/~ttsiod/index.html

**Comment by maxime-esa** [comment]
I am out of the office until 11/05/2015.




Note: This is an automated response to your message  "Re: [asn1scc] Remove
hardcoded html (#27)" sent on 02/05/2015 17:03:47.

This is the only notification you will receive while this person is away.
This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.

**Comment by maxime-esa** [comment]
I am out of the office until 11/05/2015.




Note: This is an automated response to your message  "Re: [asn1scc] Remove
hardcoded html (#27)" sent on 02/05/2015 17:02:45.

This is the only notification you will receive while this person is away.
This message and any attachments are intended for the use of the addressee or addressees only.
The unauthorised disclosure, use, dissemination or copying (either in whole or in part) of its
content is not permitted.
If you received this message in error, please notify the sender and delete it from your system.
Emails can be altered and their integrity cannot be guaranteed by the sender.

Please consider the environment before printing this email.

**Comment by maxime-esa** [comment]
Thanks. Replaced the match with a ternary.

**Pull request merged**
