### PR TITLE
[Placeholder] asn1scc as REST service

### PR DESCRIPTION
**Pull request by hcorg**
This PR is here just to trigger a discussion about asn1scc "daemon" version, so all comments are welcome.

This is definitely not a final version, but it can be merged (it's functional, but inefficient), just to let people play with it.

It's a placeholder, because proper solution would be to extract "core" functionality into a library, which would then operate on abstract I/O objects, but that requires a lot of refactoring and there is already one refactoring ongoing, so I have to wait with that :)

Unfortunately I could not use nice WCF libraries, as Mono does not properly support them (strange errors, different behavior between Mono versions etc.). General outcome: Mono + REST + HTTP POST sucks... 

So I've created basic HTTP server using System.Net classes. It currently supports only two commands: check Daemon.ExampleClient/Client.py for details.

### CODE REVIEW

**Comment by hcorg** [comment]
hmmm, nobody protests, so I assume we can move forward and implement support for such REST service in asn1scc.IDE :)

**Comment by ttsiodras** [comment]
I'll just quote you:

    "...there is already one refactoring ongoing, so I have to wait with that"

:-)

**Comment by hcorg** [comment]
that's why this PR does (almost) do not touch existing code - just creates dummy wrapper  :)

**Comment by ttsiodras** [comment]
Fair point - which is why (in theory!) it will be mergeable as-is on the final master

**Comment by hcorg** [comment]
hopefully in final master I'll be able to use some extracted during refactor module and do not create temp files etc.

**Comment by hcorg** [comment]
replaced by #127 (dedicated for V4, but it also contains changes necessary to run V3 as service, if needed)

**Pull request closed without merging**
