### PR TITLE
AppVeyor configuration added

### PR DESCRIPTION
**Pull request by hcorg**
see appveyor log: https://ci.appveyor.com/project/hcorg/asn1scc/build/3.3.20.5

currently it only builds, running tests requires some more refactoring

I've also fixed some dependencies between projects (removed dependecies definitions from sln file), so it builds using Microsoft's msbuild.

### CODE REVIEW

**Comment by ttsiodras** [comment]
That looks very promising, Konrad!

It is a major improvement to be able to modify ASN1SCC knowing that not just the Linux/OSX crowd but also the Windows ones don't have their functionality break.  I am hoping that in the end we will have another green indicator at the top of the README, alongside the CircleCI one!

**Comment by hcorg** [comment]
AppVeyor offers similar indicators, so you can put one already :D

I do not often work on Windows, but from time to time it's nice to do some refactoring using VisualStudio, so indeed CI could help keeping asn1scc working on Windows :)

I'll try to work on running tests on Windows now.

**Comment by hcorg** [comment]
Hmm, runTests.py is highly coupled with gcc/bash. I think there's nothing to gain by running it on Windows and it's quite complicated to prepare working setup on AppVeyor. So maybe just building would be enough for now.

**Comment by ttsiodras** [comment]
Feel free to patch the README to add that indicator as well!

Merged.

**Comment by hcorg** [comment]
to create that indicator you to enable AppVeyor for this repository - same as with CircleCI

Link to log shows AppVeyor integration with my fork :)

**Comment by hcorg** [comment]
(and then some guid will be generated and you can include it in README, I'm not sure if it will be visible for me - probably ownership of repo is required)

**Comment by ttsiodras** [comment]
I think it's done - I added the integration and the marker in the README. 

Have a look - all OK?

**Comment by hcorg** [comment]
Looks ok :)

**Pull request merged**
