### PR TITLE
asn1crt compilation fix for WORD_SIZE==4

### PR DESCRIPTION
**Pull request by hcorg**

### CODE REVIEW

**Comment by ttsiodras** [comment]
Spoke with George - he is in vacation, so he only glanced at this, but this was his comment:

"I do not really understand the purpose of these changes... I also don't like the fact that functions that work fine under both 32 and 64 bits environments, are changed in this pull request e.g. from

    int GetLengthInBytesOfUInt(asn1SccUint v);

to 

    int GetLengthInBytesOfUInt(asn1SccUint64 v);

...so, it seems they will work only in 64 environments now?"

**Comment by hcorg** [comment]
those were the changes I need to do to make asn1crt compile with `WORD_SIZE=4`. So 32bit env is currently not supported at all. Some changes I had to add to compile without any warnings, but those warnings pointed to some critical issues.

It's a matter of performance - keeping default in size in asn1crt as 64bit, makes all int related instructions into function calls on LEON3. (64bit ints are available on 32bit machines, but there should be possibility to easily change default asn1crt int.)

Better change would be to remove completely WORD_SIZE, stick with `int32_t` as default, and use `int64_t` only when needed.

**Comment by gmamais** [comment]
Hi,
Sorry for the delay, but I was on vacations, returned today.

**Comment by hcorg** [comment]
no problem, just returned myself :)

**Comment by hcorg** [comment]
still - turning on WORD_SIZE=4 makes auto generated test cases not pass
problem - I've defined UInt32 type, yet asn1crt internally uses signed type :/ 
probably without big changes in asn1scc generator itself it can't be done

it's not priority, I've just wanted to compare performance on 32bit machines without native 64bit support

**Pull request merged**
